### ISSUE TITLE
How to render layout/index.swig ?

### ISSUE THREAD

**Issue by KudoKhang** [Harendra1993/vita#1]
I followed your instructions but it doesn't work, index.swig doesn't render to blog. I tried many ways but failed.
![image](https://user-images.githubusercontent.com/24488797/115174937-5bf24300-a0f4-11eb-916c-f3bf6e3afa72.png)

**Comment by fmontenegro0510** [comment]
Same situation, please anywone can help us?

**Comment by KudoKhang** [comment]
Check "hexo-renderer-swig" already exists in package.json ? If not, install "npm install hexo-renderer-swig --save"
*Default it have only "hexo-renderer-ejs" "hexo-renderer-stylus" and "hexo-renderer-marked"* :+1: 

![image](https://user-images.githubusercontent.com/24488797/123449548-fe073d80-d605-11eb-8fd2-b2bbe13eb80f.png)
